# Configuration for Label Actions - remove label id

📣 Announcement:
  discussions:
    unlabel:
      - '📣 Announcement'

👂 Feedback Wanted:
  discussions:
    unlabel:
      - '👂 Feedback Wanted'

👨‍💻 In the Backlog:
  discussions:
    unlabel:
      - '👨‍💻 In the Backlog'

❗️ Incident:
  discussions:
    unlabel:
      - '❗️ Incident'

🛣️ On the Roadmap:
  discussions:
    unlabel:
      - '🛣️ On the Roadmap'

🚀 Shipped:
  discussions:
    unlabel:
      - '🚀 Shipped'
