labels: [Codespaces]
body:
- type: dropdown
  id: topic
  attributes:
    label: Select Topic Area
    description: What would you like to discuss?
    options:
      - "Question"
      - "Product Feedback"
      - "Bug"
      - "Show & Tell"
      - "General"
  validations:
    required: true
- type: textarea
  id: text
  attributes:
    label: Body
    description: Start your discussion!
  validations:
    required: true
