body:
- type: markdown
  attributes:
    value: |
      #### Explore our [Copilot FAQs](https://github.com/orgs/community/discussions/144674) and [GitHub Docs](https://docs.github.com/en/copilot) for comprehensive guidance!
      - ðŸ’¡ **Quick Tip:** For general development questions or detailed code issues, try [Chat with Copilot](https://docs.github.com/en/enterprise-cloud@latest/copilot/using-github-copilot/copilot-chat/asking-github-copilot-questions-in-github) first, it might have the answer you need before posting here.
      - ðŸ› ï¸ For bugs and feature requests related to Copilot in VS Code, please open an issue in our [VS Code Copilot repo](https://github.com/microsoft/vscode-copilot-release/issues).
      - ðŸ” Are you a student/teacher looking to enable Copilot Pro? [Read our guide](https://gh.io/faq-nd-copilot)
- type: dropdown
  attributes:
    label: Select Topic Area
    description: What would you like to discuss about GitHub Copilot? Choose your topic area. 
    options:
      - Question
      - Product Feedback
      - Bug 
      - General
  validations:
    required: true
- type: dropdown
  id: feature-area
  attributes:
    label: Copilot Feature Area
    description: Which Copilot feature or product area is your discussion related to?
    options:
      - General
      - Copilot in GitHub
      - Copilot Workspace
      - Copilot Agent Mode 
      - Copilot Enterprise
      - Account Related 
      - VS Code
      - Visual Studio
      - JetBrains & Xcode
  validations:
    required: true
- type: textarea
  attributes:
    label: Body
    description: Start your discussion!
    placeholder: >-
      Provide a detailed description of your discussion (e.g., What issue are you facing? What feedback do you have? What question do you need answered?)
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      #### Don't forget to mark an [answer as "solved"](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/participating-in-a-discussion#marking-a-comment-as-an-answer) to help others with similar questions. âœ…
