title: "<Your question or feedback about the GitHub Discussions product>"
labels: [Discussions]
body:
- type: markdown
  attributes: 
   value: |
     ⚠️ This category is solely for discussions and feedback on [the GitHub Discussions product](https://github.com/features/discussions). ⚠️

     The Discussions category is NOT meant to be a place for any old discussion regarding GitHub or programming — [the General category](https://github.com/orgs/community/discussions/categories/general) is a more appropriate space for misc topics. To ensure you receive a timely response and connect with the proper team(s), please post in the correct category by using the corresponding product category. 

     NOTE: If you post in this category about topics other than GitHub Discussions, your post may be moved or deleted without warning. Users who post spam or violate of our [Code of Conduct](https://github.com/github/.github/blob/95e9dcb0b8b70a25cdb75de29f600812a07eb996/CODE_OF_CONDUCT.md) will be blocked.
- type: dropdown
  attributes:
    label: Select Topic Area
    description: What would you like to discuss?
    options:
      - "Product Feedback"
      - "Question"
      - "Bug"
      - "Show & Tell"
      - "General"
  validations:
    required: true
- type: textarea
  attributes:
    label: Body
    description: Start your discussion!
  validations:
    required: true
