title: "<Your question or feedback about the GitHub Discussions product>"
labels: [Discussions]
body:
  - type: markdown
    attributes: 
      value: |
        ⚠️ This category is solely for discussions and feedback on [the GitHub Discussions product](https://github.com/features/discussions). ⚠️

        [GitHub Discussions](https://github.com/features/discussions) is a product within GitHub that allows users to talk, ask questions, and share ideas. Discussions are meant for open-ended conversations.

        ### ✅ Dos - Use this category if your post is about
        - How to enable or configure **GitHub Discussions** in a repository or organization
        - Questions about **GitHub Discussions** features, such as marking answers, organizing threads or using moderation tools.
        - Bugs or issues specifically related to **GitHub Discussions** 🐞
        - Suggestions or feedback to improve the **GitHub Discussions** product 💬

        ### 🚫 Don'ts - Please, don't use this category for:
        - General troubleshooting, water cooler conversations or off-topic questions - have you tried General or Programming Help?
        - Feedback that doesn't directly relate to _GitHub Discussions_, that feedback belong somewhere else, use this [quick guide](https://github.com/orgs/community/discussions/151702) to help.

        ### 📚 Need help understanding how GitHub Discussions works?  
        Read the official documentation: [GitHub Discussions Docs](https://docs.github.com/en/discussions)

  - type: dropdown
    attributes:
      label: "Discussion Type"
      description: What would you like to discuss?
      options:
        - "Product Feedback"
        - "Question"
        - "Bug"
        - "Show & Tell"
        - "General"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Discussion Content"
      description: Start your discussion!
    validations:
      pattern: "^.{1000,}$"
      regexFlags: "s"
      note: "Must have at least 1000 characters"
