labels: ["GitHub Education", "source:ui"]
body:
    - type: markdown
      attributes:
        value: |
          #### Welcome! Before You Create a New Post...
          Before you post, check our [SDP FAQ](https://gh.io/sdp-faq-nd) for answers to common questions. If your question isn't covered, select a Feature/Topic Area and start your discussion.
          We're here to help, share, and learn together—ask questions, offer advice, or connect with other students and educators!
          **Please do not post personal information or images of your evidence.**
    - type: markdown
      attributes:
        value: |
          > [!IMPORTANT]
          > New activations of **Copilot Student, Pro, and Pro Plus** are currently **paused**. 
          > 
          > Your GitHub Education verification is active and **has not been removed**. When signups resume, you’ll be able to activate the Education benefit if you’re still eligible, and **Copilot Free remains available** in the meantime.
          > 
          > We don’t have an estimated timeframe to share yet. Updates will be posted in the [community announcement](https://github.com/orgs/community/discussions/192963). Thanks for your patience while we work to make this experience more reliable.
    - type: dropdown
      attributes:
        label: "🏷️ Discussion Type"
        description: What would you like to discuss?
        options:
          - Bug
          - Product Feedback
          - Question
      validations:
        required: true
    - type: dropdown
      attributes:
        label: "💬 Feature/Topic Area"
        description: Which area best matches your post? (If applicable)
        options:
          - Verification Help & Guidance
          - Evidence and Image Capture
          - School Email/Domain Issues
          - Form Errors & Technical Issues
          - Benefit Activation/Waiting
          - Billing & Payment Issues
          - Re-verification/Repeat Application
          - Redeem Benefits/Offers
          - GitHub Classroom
          - Career & Internship Advice
          - Student Events & Hackathons
          - Study Projects & Resources
          - Campus Experts
          - Other
      validations:
        required: true
    - type: textarea
      id: conversation
      attributes:
        label: Hi everyone,
        description:
      validations:
        required: true
    - type: markdown
      attributes:
          value: |
            #### Anything else I could do to make my experience here more rewarding? 🤔
            * Remember to mark an [answer as "solved"](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/participating-in-a-discussion#marking-a-comment-as-an-answer) to help others with similar questions. ✅
            * Praise generously 💖 Thank members who have helped you and continue to support others within the community. ✨
