labels: [Programming Help]
body:
- type: markdown
  attributes:
    value: Start your discussion!
  validations:
    required: true
- type: textarea
  attributes:
    label: Body
    description: Start your discussion!
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Guidelines
    options:
      - label: I have read and understood this category's [guidelines](https://github.com/orgs/community/discussions/51384) before making this post.
        required: true
