#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/github"

owner = "fennelmarkets"
repo = "community"

body =<<BODY
**💬 Your Product Feedback Has Been Submitted 🎉**

Thank you for taking the time to share your insights with us! Your feedback is invaluable as we build
a better Fennel experience for all our users.

**Here's what you can expect moving forward ⏩**
- Your input will be carefully reviewed and cataloged by members of our product teams. 
  - Due to the high volume of submissions, we may not always be able to provide individual responses.
  - Rest assured, your feedback will help chart our course for product improvements.
- Other users may engage with your post, sharing their own perspectives or experiences. 
- Fennel staff may reach out for further clarification or insight. 
  - We may 'Answer' your discussion if there is a current solution, workaround, or roadmap/changelog
  post related to the feedback.

**Where to look to see what's shipping 👀**
- Check the [Announcements](https://github.com/orgs/fennelmarkets/discussions/categories/announcements) for updates on the latest Fennel features,
enhancements, and calls for feedback.

**What you can do in the meantime 💻**
- Upvote and comment on other user feedback Discussions that resonate with you.
- Add more information at any point! Useful details include: use cases, relevant labels, desired
outcomes, and any accompanying screenshots.

As a member of the Fennel community, your participation is essential. While we can't promise that
every suggestion will be implemented, we want to emphasize that your feedback is instrumental in
guiding our decisions and priorities.

Thank you once again for your contribution to making Fennel even better! We're grateful for your
ongoing support and collaboration in shaping the future of our platform.
BODY

discussion_number = ENV['DISCUSSION_NUMBER']
node_id = ENV['NODE_ID']

puts "Checking #{node_id} for an existing feedback comment"

exit unless Discussion.should_comment?(discussion_number: discussion_number, owner: owner, repo: repo)

discussion = Discussion.new(node_id)
discussion.add_comment(body: body)
