#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/github"

stale_label_id = "LA_kwDOEfmk4M8AAAABYVCU-g"
owner = "community"
repo = "community"

body =<<BODY
🕒 **Discussion Activity Reminder** 🕒

This Discussion has been labeled as dormant by an automated system for having no activity in the last 60 days. Please consider one the following actions:

1️⃣ Close as Out of Date: If the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: Share additional details or context — or let the community know if you've found a solution on your own.

3️⃣ Mark a Reply as Answer: If your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬
BODY

discussions = Discussion.all(owner:, repo:)
puts "All: #{discussions.count}"

unlabelled = discussions.reject { |d| d.labelled }
puts "Unlabelled: #{unlabelled.count}"
unlabelled.each do |discussion|
  puts "#{discussion.url} - #{discussion.title}"
  result = discussion.add_comment(body: body)
  if errors = result.dig("errors")
    puts "#{errors.dig(0, "type")}: #{errors.dig(0, "message")}"
    exit
  end
  discussion.add_label(label_id: stale_label_id)

  sleep 10
end
