#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/github"

stale_label_id = "LA_kwDOEfmk4M8AAAABYVCU-g"
owner = "community"
repo = "community"
only_these_categories = ["Copilot"]

categories = Category.all(owner:, repo:).select { |c| only_these_categories.include?(c.name) }

categories.map do |category|
  category.discussions = Discussion.all(owner:, repo:, category:)
end

categories.each do |category|
  category.discussions.each do |discussion|
    puts "#{discussion.url},#{discussion.title}"
    result = discussion.add_comment(body: body)
    if errors = result.dig("errors")
      puts "#{errors.dig(0, "type")}: #{errors.dig(0, "message")}"
      sleep 1.2
      next
    end
    #discussion.add_label(label_id: stale_label_id)

    sleep 1.2
  end
end
