#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/github"

stale_label_id = "LA_kwDOEfmk4M8AAAABYVCU-g"
owner = "community"
repo = "community"
only_these_categories = ["Copilot", "Projects and Issues", "Accessibility"]

categories = Category.all(owner:, repo:).select { |c| only_these_categories.include?(c.name) }

categories.map do |category|
  category.discussions = Discussion.all(owner:, repo:, category:)
end

categories.each do |c|
  puts "#{c.name} has #{c.discussions.count} eligible discussion(s)"
end

# for initial testing, don't modify any discussions
#categories.each do |category|
#  category.discussions.each do |discussion|
#    discussion.add_comment(body: "This is automated")
#    discussion.add_label(label_id: stale_label_id)
#  end
#end
