#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/github"

stale_label_id = "LA_kwDOMkvYrs8AAAABtZoJIg"
owner = "fennelmarkets"
repo = "community"

node_id = ENV['NODE_ID']
puts "Removing the inactive label from #{node_id}"
Discussion.remove_label(node_id: node_id, label_id: stale_label_id)
