Ambulan Banjarmasin Kunsultan Kesehatan         

Jl.A.Yani KM.3,7 Komplek. Kelapa No.53 RT.19 Kelurahan, Kebun Bunga, Kecamatan Banjarmasin Timur. Kota Banjarmasin, Kalimantan Selatan 70235 
https://g.page/Ambulan-Banjarmasin, 
https://www.facebook.com/ambulanbanjarmasin, 
https://www.tiktok.com/@ambulanbanjarmasin , 
https://wa.me/628125353232 , https://www.linkedin.com/in/ambulan-Banjarmasin , 
https://t.me/Ambulan_Banjarmasin,  Indonesia   

AMBULAN  BANJARMASIN ADALAH LAYANAN KESEHATAN DARURAT PASEIN Dan PEMULASARAAN JENAZAH ANTAR KOTA ANTAR PROVINSI Dan KAMI MELAYANI HOME CARE SEPERTI PERAWATAN LUKA POST OPERASI, STOMA, GANGREN, DECUBITUS, DIABETES MELETUS, Dll     

On Call 24 Jam By Wa: ☎️ 0812 5353 232     

LAYANAN KU IBADAH KU   👳👳👳 
MUDAHKAN MENUJU SURGA 🤲🤲🤲     

#ambulanbanjarmasin   #ambulanbanjarmasin232 
#ambulanbanjarmasin232 @ambulanbanjarmasin232name: Remove the inactive label

on:
  discussion_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      discussions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Bundle install
        run: bundle install

      - name: Remove the label
        run: .github/actions/remove_inactive_label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ID: ${{ github.event.discussion.node_id }}
