name: Update current incident discussion with new information

on:
  repository_dispatch:
    types: [incident-public-update]

jobs:
  update_discussion:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      discussions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@7bae1d00b5db9166f4f0fc47985a3a5702cb58f0

      - name: Bundle install
        run: bundle install

      - name: Get incident URL slug
        id: incident_slug
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const url = "${{ github.event.client_payload.incidentLink }}"
            const slug = url.split('/').pop();
            return slug

      - name: Add comment to incident discussion
        id: add_comment
        run: .github/actions/update_incident_discussion.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INCIDENT_SLUG: ${{ steps.incident_slug.outputs.result }}
          INCIDENT_MESSAGE: ${{ github.event.client_payload.message }}
